FROM python:3.10-slim

WORKDIR /app

COPY infra/docker/requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

COPY app/ ./app/

# Add the app directory to the python path
ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "app/ui/main.py", "--server.port=8501", "--server.address=0.0.0.0"]